### PR TITLE
final urls for CP Europe

### PR DESCRIPTION
**Pull request by rmarinleal**
* Valid for v1 requests

### CODE REVIEW

**Review by benfterpay — CHANGES_REQUESTED** [review]
@rmarinleal please set the base branch to `master` for this one, and bump the patch version. From `master` we can merge down into `downgrade-to-api-v1`.

**Comment by pgarcess** [comment]
Setting the PR with the config Base:master & Compare:final_urls, I receive the error:"Pull request creation failed. Validation failed: You can't perform that action at this time."

**Comment by rmarinleal** [comment]
Hi @benfterpay, 

If I merge this branch with master, all the changes made on `downgrade-to-api-v1` will be merged to, so I'm not quite sure you want it.

you can se here the changes:
https://github.com/afterpay/sdk-php/compare/master...final_urls

I you want it, please launch the PR of these two branches and the later the merge of `master` into `downgrade-to-api-v1`

Thanks!!

**Comment by benfterpay** [comment]
Good point @rmarinleal, ideally `final_urls` should have been branched from `master`. Never mind, we can just cherry-pick the changes later.

**Review by benfterpay — APPROVED** [review]

**Pull request merged**
